watchdog:
  ros__parameters:
    q_max: [
        2.8798,
        2.9671,
        2.7576,
        2.8798,
        0.5236,
        0.2618,
        2.8798,
        0.5236,
        2.7576,
        2.8798,
        0.5236,
        0.2618,
        2.618,
        2.6704,
        2.2515,
        2.618,
        2.0944,
        1.972222054,
        1.614429558,
        1.614429558,
        2.6704,
        1.5882,
        2.618,
        2.0944,
        1.972222054,
        1.614429558,
        1.614429558
    ]
    q_min: [ -2.5307,
            -0.5236,
            -2.7576,
            -0.087267,
            -0.87267,
            -0.2618,
            -2.5307,
            -2.9671,
            -2.7576,
            -0.087267,
            -0.87267,
            -0.2618,
            -2.618,
            -3.0892,
            -1.5882,
            -2.618,
            -1.0472,
            -1.972222054,
            -1.614429558,
            -1.614429558,
            -3.0892,
            -2.2515,
            -2.618,
            -1.0472,
            -1.972222054,
            -1.614429558,
            -1.614429558
            ]
        # Extracted from g1_description urdf
    margin_duration: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03, 0.03]
        # See https://github.com/inria-paris-robotics-lab/go2_control_interface/issues/11#issuecomment-2995477021
