watchdog:
  ros__parameters:
    # FL, FR, RL, RR
    q_max: [ 0.86, 3.490, -0.837,
             0.86, 3.490, -0.837,
             0.86, 4.537, -0.837,
             0.86, 4.537, -0.837]
    q_min: [ -0.86, -1.570, -2.84,
             -0.86, -1.570, -2.84,
             -0.86, -0.523, -2.84,
             -0.86, -0.523, -2.84]
        # Extracted from go2_description urdf
    margin_duration: [0.06, 0.06, 0.04,
                      0.06, 0.06, 0.04,
                      0.06, 0.06, 0.04,
                      0.06, 0.06, 0.04]
        # See https://github.com/inria-paris-robotics-lab/unitree_control_interface/issues/11#issuecomment-2995477021
